In [1]:
# ==========================================
# Project 2 - Data Collection
# MAE by Maybank Google Play Reviews
# ==========================================

import pandas as pd
from google_play_scraper import reviews, Sort

In [2]:
# App ID for MAE by Maybank
APP_ID = "com.maybank2u.life"

result, continuation_token = reviews(
    APP_ID,
    lang="en",
    country="my",
    sort=Sort.NEWEST,
    count=200
)

print("Number of reviews:", len(result))

Number of reviews: 200

In [3]:
# Display results
result[0]

{'reviewId': '050596a8-c51c-4fdd-821a-0f2aef921615',
 'userName': 'Muhamad Ikhmal Hijaz Bin Zulkefli',
 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIV3J-oFpabMO0zumqzb-J-IBP2p-sKSf8FWu8jZhRzsZlzFQ=mo',
 'content': 'A dependable banking app that makes handling money pretty straightforward. The interface is easy to use, and transactions are fast and secure',
 'score': 5,
 'thumbsUpCount': 0,
 'reviewCreatedVersion': '0.9.47',
 'at': datetime.datetime(2026, 6, 28, 16, 8),
 'replyContent': None,
 'repliedAt': None,
 'appVersion': '0.9.47'}

In [4]:
# Convert to DataFrame
df = pd.DataFrame(result)

df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,050596a8-c51c-4fdd-821a-0f2aef921615,Muhamad Ikhmal Hijaz Bin Zulkefli,https://play-lh.googleusercontent.com/a/ACg8oc...,A dependable banking app that makes handling m...,5,0,0.9.47,2026-06-28 16:08:00,NaN,NaT,0.9.47
1,16cdbb68-29ca-40cd-8e46-263d8d5c6356,Kokoroko Hehehe,https://play-lh.googleusercontent.com/a/ACg8oc...,very good app,5,0,NaN,2026-06-28 16:00:46,NaN,NaT,NaN
2,24983606-de39-47e4-b600-5f49a256fca2,Amarjit kaur,https://play-lh.googleusercontent.com/a-/ALV-U...,Amazing service and great experience! 😊 Thank ...,5,0,0.9.47,2026-06-28 15:45:19,NaN,NaT,0.9.47
3,0f44892c-a7d3-4b44-b55f-9ed72964926c,Tsu,https://play-lh.googleusercontent.com/a-/ALV-U...,I gave this app a chance it works up until the...,2,6,0.9.47,2026-06-28 11:33:30,"Hi, sorry for the inconvenience.We regret on t...",2023-01-13 13:38:32,0.9.47
4,683d9e48-3f16-4f82-891e-e31031aa6019,Aten Klopp,https://play-lh.googleusercontent.com/a/ACg8oc...,"Can't reload my phone credit through FPX, noti...",1,0,0.9.47,2026-06-28 09:28:59,"Hi, sorry for the inconvenience. Rest assured,...",2026-05-03 10:44:52,0.9.47

In [5]:
# Check columns
df.columns

Index(['reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion'],
      dtype='str')

In [6]:
df = df[
    [
        "reviewId",
        "content",
        "score",
        "at",
        "thumbsUpCount",
        "appVersion"
    ]
]

In [7]:
df.columns = [
    "review_id",
    "review",
    "rating",
    "review_date",
    "thumbs_up",
    "app_version"
]

In [8]:
df.head()

,review_id,review,rating,review_date,thumbs_up,app_version
0,050596a8-c51c-4fdd-821a-0f2aef921615,A dependable banking app that makes handling m...,5,2026-06-28 16:08:00,0,0.9.47
1,16cdbb68-29ca-40cd-8e46-263d8d5c6356,very good app,5,2026-06-28 16:00:46,0,NaN
2,24983606-de39-47e4-b600-5f49a256fca2,Amazing service and great experience! 😊 Thank ...,5,2026-06-28 15:45:19,0,0.9.47
3,0f44892c-a7d3-4b44-b55f-9ed72964926c,I gave this app a chance it works up until the...,2,2026-06-28 11:33:30,6,0.9.47
4,683d9e48-3f16-4f82-891e-e31031aa6019,"Can't reload my phone credit through FPX, noti...",1,2026-06-28 09:28:59,0,0.9.47

Data Validation

In [9]:
# Check dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    200 non-null    str
 1   review       200 non-null    str
 2   rating       200 non-null    int64
 3   review_date  200 non-null    datetime64[us]
 4   thumbs_up    200 non-null    int64
 5   app_version  150 non-null    str
dtypes: datetime64[us](1), int64(2), str(3)
memory usage: 40.8 KB

In [10]:
# Check for missing values
df.isnull().sum()

review_id       0
review          0
rating          0
review_date     0
thumbs_up       0
app_version    50
dtype: int64

In [11]:
# Check for duplicate review IDs
df.duplicated(subset=["review_id"]).sum()

np.int64(0)

In [ ]:
# Rating Distribution
df["rating"].value_counts().sort_index()

rating
1     41
2      9
3     13
4      3
5    134
Name: count, dtype: int64

In [14]:
# Review Length
df["review"].str.len().describe()

count    200.00000
mean     119.32000
std      122.63984
min        3.00000
25%       28.75000
50%       76.00000
75%      164.25000
max      500.00000
Name: review, dtype: float64

In [15]:
# Display the first 10 rows
df.sample(10)

,review_id,review,rating,review_date,thumbs_up,app_version
19,8fefeaf1-3660-4f0c-8d6b-f15c073cd5c5,Maybank2u is a reliable and easy-to-use bankin...,5,2026-06-26 22:40:04,0,NaN
20,b855ce68-9400-4796-876b-645995289e64,Apps ni melibatkan duit yang disimpan pelangga...,1,2026-06-26 21:58:17,0,NaN
87,f39c2af8-2a8e-4147-95f2-53c351e9e9cf,nice apps,5,2026-06-20 18:39:24,0,0.9.47
138,4a74dbd7-d78b-429f-acab-493720b9f0d6,transfer money is more easy here,5,2026-06-16 01:47:51,0,NaN
11,43e40ab0-4499-4dd2-964c-9b8e2b25c1cb,I've been using Maybank2u for daily banking li...,5,2026-06-27 22:04:24,0,NaN
68,bbc2ccfb-89b6-473d-a8e7-b28a140ada9f,ok good,5,2026-06-22 23:22:50,0,0.9.47
179,67d93d86-f5a2-446c-9b10-017bb1ae7556,good apps,5,2026-06-11 07:49:43,0,0.9.47
106,a935ea6f-ca62-4520-809e-832b623b1be7,MAE wallet and QR Pay make cashless life easy....,5,2026-06-18 21:33:23,0,0.9.47
141,09320027-aaa4-46a7-8439-e11f24c4bda4,why i can't change the transfer limit?????,3,2026-06-15 13:24:08,0,0.9.47
113,084abe88-8ade-4a44-84a6-6339204beae7,Maybank2u is a highly practical mobile banking...,5,2026-06-18 14:17:04,0,NaN

After test 200 data, start download 5000 data

In [16]:
from tqdm import tqdm

In [17]:
# Create Variable
APP_ID = "com.maybank2u.life"

TARGET_REVIEWS = 5000

all_reviews = []

continuation_token = None

In [18]:

# Download Reviews in a loop
while len(all_reviews) < TARGET_REVIEWS:

    result, continuation_token = reviews(
        APP_ID,
        lang="en",
        country="my",
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )

    if not result:
        print("No more reviews available.")
        break

    all_reviews.extend(result)

    print(f"Downloaded {len(all_reviews)} reviews...")

Downloaded 200 reviews...
Downloaded 400 reviews...
Downloaded 600 reviews...
Downloaded 800 reviews...
Downloaded 1000 reviews...
Downloaded 1200 reviews...
Downloaded 1400 reviews...
Downloaded 1600 reviews...
Downloaded 1800 reviews...
Downloaded 2000 reviews...
Downloaded 2200 reviews...
Downloaded 2400 reviews...
Downloaded 2600 reviews...
Downloaded 2800 reviews...
Downloaded 3000 reviews...
Downloaded 3200 reviews...
Downloaded 3400 reviews...
Downloaded 3600 reviews...
Downloaded 3800 reviews...
Downloaded 4000 reviews...
Downloaded 4200 reviews...
Downloaded 4400 reviews...
Downloaded 4600 reviews...
Downloaded 4800 reviews...
Downloaded 5000 reviews...

In [19]:
# Convert to DataFrame
df = pd.DataFrame(all_reviews)

print(df.shape)

(5000, 11)

In [20]:
df = df[
    [
        "reviewId",
        "content",
        "score",
        "at",
        "appVersion"
    ]
]

In [21]:
df.columns = [
    "review_id",
    "review",
    "rating",
    "review_date",
    "app_version"
]

In [22]:
df = df.drop_duplicates(subset=["review"])

In [23]:
print(df.shape)

(4155, 5)

In [24]:
df.to_csv(
    "../data/raw_data/mae_reviews.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset saved successfully!")

Dataset saved successfully!